---
title: "Resume"
output: html_document
---

### --------- Education ---------  
  

<font size="3">
**Columbia University Mailman School of Public Health, New York, NY**  
_Expected Graduation: May 2020_  
_Master in Public Health in Epidemiology, Epidemiology of Chronic Diseases Certificate_  

**Boston College, Chestnut Hill, MA**  
_Graduated: May 2016_  
_BS in Biochemistry_  

**Monash University, Melbourne, Australia**  
_Study Abroad: Feb - Jun 2015_  
</font>  

### --------- Professional Experience ---------  
  

<font size="3">
**Columbia University Mailman School of Public Health, New York, NY**  
_Sept 2019 - Present_  
_Teaching Assistant, Research Methods and Applications, Quantitative Foundations_  
- Led a weekly lab section with a class of students to review lecture material and practice problems  
- Held weekly and additional office hours to provide support to students  
- Piloted homework assignments and exams to test and revise questions for clarity and difficulty  
  
**Columbia School of Nursing, New York, NY**  
_Apr 2019 - Present_  
_Research Assistant, mHealth for People Living with HIV_  
- Designed and implemented a REDCap database to replace existing Access database and fit with team’s workflow  
- Evaluated Access database and reviewed its pain points and functionalities with research team  
- Developed a Standard Operating Procedure (SOP) and visual guide for using REDCap for research team use  
- Resolved a number of REDCap issues encountered in the research team’s other studies  
- Recruited, screened, and conducted visits with study participants  

**Beth Israel Deaconess Medical Center, Boston, MA**  
_Sept 2016 - Sept 2018_  
_Clinical Research Assistant, Department of Nephrology_  
- Managed the Glomerular Kidney Disease Registry study and prepared project plan and IRB documents  
- Conducted research to create REDCap database and biobank protocols and created the SOP  
- Collaborated with research administrators and legal team to establish data transfer agreements  
- Helped design GlomCon website (www.glomcon.org) and managed weekly online case conferences  

**Boston College, Chestnut Hill, MA**  
_May 2014 - May 2016_  
_Research Assistant, Independent Research Study_  
- Designed research study examining effect of biased hemisphere activation on the processing of language  
- Received IRB approval for the research study; designed study tasks using E-Prime and Word; recruited participants; collected and analyzed data using SPSS  
</font>  

### --------- Publications ---------  
  

<font size="3">
Poyan Mehr, A., Sadeghi-Najafabadi, M., **Chau, K.**, Messmer, J., Pai, R., Roy, N., Friedman, D., Pollak, M.R., Schlondorff, J., Naljayan, M., Singh, T., Lecker, S.H., Rodby, R., Germain, M., Rennke, H., Stillman, I.E. (2019) “The Glomerular Disease Study and Trial Consortium: A Grassroots Initiative to Foster Collaboration and Innovation.” KIReports. 1:4, pp.20-29.  
</font>  

### --------- Skills and Certifications ---------  
  

<font size="3">
**Computer:** REDCap; SAS; R; GIS; Access; Microsoft Office Suite; Google Documents; SQL; Python

**Certifications:** CITI Human Subjects Protection, HIPAA

**Languages:** Cantonese (conversational proficiency)  
</font>  

